packages:
  - name: ip
    functions:
      - name: echo
        runtime: 'nodejs:18'
        #main: 'index.js'
        web: true # expose over HTTPS
        limits:
          timeout: 1000 # ms
          memory: 128 # MB
